name: gigagan
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - accelerate
    - beartype
    - einops>=0.6
    - ema-pytorch
    - kornia
    - numerize
    - open-clip-torch>=2.0.0,<3.0.0
    - pillow
    - torch>=1.6
    - torchvision
    - tqdm
    - hydra-core
