---
defaults:
  - model: gigagan-lite

data_dir: ../PrivacyGANRes/data/
image_size: ${oc.select:model.generator.input_image_size,${model.generator.image_size}}
num_workers: 2

min_occurences: 30
batch_size: 4
steps: 100
grad_accum_every: 8

model:
  learning_rate: 2e-4
  discr_aux_recon_loss_weight: 1.0
  multiscale_divergence_loss_weight: 0.1
  num_samples: 32
  amp: true
