---
defaults:
  - model: gigagan-tiny
  - _self_

load_latest_model: true
num_workers: 2
data_dir: ../PrivacyGANRes/data/
image_size: ${oc.select:model.generator.input_image_size,${model.generator.image_size}}
min_occurences: 30
cond_dim: ???  # changes based on `min_occurrence`

batch_size: 32
grad_accum_every: 8  # aka num of sequential batches (reduces memory overhead)
steps: 100

model:
  learning_rate: 3e-4
  discr_aux_recon_loss_weight: 0.5
  multiscale_divergence_loss_weight: 0.1
  num_samples: ${batch_size}
  save_and_sample_every: 500
  amp: true
  accelerate_kwargs:
    gradient_accumulation_steps: ${grad_accum_every}
